.github/workflows/gnostr-relay.yml

diff --git a/.github/workflows/gnostr-relay.yml b/.github/workflows/gnostr-relay.yml
--- a/.github/workflows/gnostr-relay.yml
+++ b/.github/workflows/gnostr-relay.yml
@@ -1,4 +1,4 @@
-name: gnostr-bot.yml
+name: gnostr-relay.yml
 
 # Controls when the action will run.
 on:
@@ -14,7 +14,7 @@ permissions:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  gnostr-bot:
+  gnostr-relay:
     env:
       FORCE: "--force"
       GNOSTR: "gnostr"
@@ -64,26 +64,18 @@ jobs:
             ~/.cargo
           key: ${{ runner.os }}-cargo-${{ matrix.rustup }}
 
-      - name: Restore target
-        id: cache-target-restore
-        uses: actions/cache/restore@v3
-        if: ${{ !env.ACT }}
-        with:
-          path: |
-            target
-          key: ${{ runner.os }}-target-${{ matrix.rustup }}
-
       - uses: actions/checkout@v3
         with:
-          submodules: 'true'
+          submodules: 'false'
           set-safe-directory: 'true'
           fetch-depth: '0'
-          fetch-tags: 'true'
+          fetch-tags: 'false'
 
       - run: printenv || true
 
       - run: rustup default ${{ matrix.rustup }}
 
+      - run: cargo clean ##set cron
       - run: cargo search gnostr --limit 100
 
       - run: cargo install cargo-binstall@main || true
@@ -110,28 +102,55 @@ jobs:
       - run: |
           gnostr -d ${{ env.POW }} \
           -r ${{ env.DAMUS }} \
-          --nsec "$(gnostr --hash '')" \
+          --nsec "$(gnostr-sha256 '$GITHUB_REPOSITORY_ID')" \
           set-metadata \
-          -n gnostr \
-          -a gnostr://$(gnostr-weeble)/$(gnostr-blockheight) \
+          -n gnostr-bot \
+          -a "$GITHUB_REPOSITORY_OWNER $(gnostr-weeble)/$(gnostr-blockheight) \#$GITHUB_REPOSITORY_ID" \
+          -t ${{ matrix.os }} \
+          -t ${{ matrix.rustup }} \
+          -t "$GITHUB_REPOSITORY" \
+          -t "$GITHUB_WORKFLOW" \
+          -t "$GITHUB_WORKFLOW_ID" \
+          -t "$GITHUB_WORKFLOW_SHA" \
+          -t "$GITHUB_WORKFLOW_REF" \
+          -t "$GITHUB_REF" \
+          -t "$GITHUB_RUN_ID" \
+          -t "gnostr-bot" \
+          -t "gnostr" \
+          -t "$GITHUB_REPOSITORY_OWNER" \
+          -t "$(date +%s)" \
+          -t "$RUNNER_ENVIRONMENT" \
+          -t "$RUNNER_OS" \
+          -t "$(gnostr-weeble)" \
+          -t "$(gnostr-blockheight)" \
+          -t "$(gnostr-wobble)" \
           -p "https://avatars.githubusercontent.com/u/135379339?s=400&u=11cb72cccbc2b13252867099546074c50caef1ae&v=4" \
           -b "https://raw.githubusercontent.com/gnostr-org/gnostr-icons/refs/heads/master/banner/1024x341.png" || true
         if: matrix.os == 'macos-latest'
 
       - run: |
-          gnostr ngit --nsec $(gnostr --hash '') fetch
-        if: matrix.os == 'macos-latest'
+          gnostr --hash "" ngit fetch
 
       - run: |
-          EVENT=$(gnostr --nsec $(gnostr --hash '') \
+          EVENT=$(gnostr --nsec "$(gnostr-sha256 '$GITHUB_REPOSITORY_ID')" \
             -d ${{ env.POW }} \
             -r ${{ env.DAMUS }} \
             -r ${{ env.NOS }} \
             custom-event \
             -k 1 \
-            -c "$(gnostr-weeble)/$(gnostr-blockheight)/$(gnostr-wobble)" \
-            -t "a|blah" \
-            -t "a|$(date +%s)" \
+            -c "$(gnostr-weeble)/$(gnostr-blockheight)/$(gnostr-wobble) \#$GITHUB_REPOSITORY_ID" \
+            -t "$GITHUB_REPOSITORY" \
+            -t "$GITHUB_WORKFLOW" \
+            -t "$GITHUB_WORKFLOW_ID" \
+            -t "$GITHUB_WORKFLOW_SHA" \
+            -t "$GITHUB_WORKFLOW_REF" \
+            -t "$GITHUB_REF" \
+            -t "$GITHUB_RUN_ID" \
+            -t "gnostr-bot" \
+            -t "$GITHUB_REPOSITORY_OWNER" \
+            -t "$(date +%s)" \
+            -t "$RUNNER_ENVIRONMENT" \
+            -t "$RUNNER_OS" \
             -t "$(gnostr-weeble)" \
             -t "$(gnostr-blockheight)" \
             -t "$(gnostr-wobble)" \
@@ -139,12 +158,11 @@ jobs:
             export EVENT=$EVENT && \
             NOTE=$(gnostr convert-key -p note -k $EVENT || true) || true && \
             export NOTE=$NOTE && echo $NOTE && echo $EVENT && \
-            curl https://nostr.band/$NOTE
-        if: matrix.os == 'macos-latest'
+            COMMAND="curl https://nostr.band/$NOTE" && echo $COMMAND && $COMMAND
+        if: matrix.os == 'ubuntu-latest'
 
       - run: |
-          cargo t
-        if: matrix.os == 'macos-latest'
+          cargo t -- --no-capture
 
       - run: |
           printenv
@@ -153,7 +171,7 @@ jobs:
         uses: Tiryoh/gha-jobid-action@v1.4.0
         id: jobs
         with:
-          job_name: "gnostr-relay (${{ matrix.os }}, ${{ matrix.rustup }})" # input job.<job-id>.name and matrix here.
+          job_name: "gnostr-bot (${{ matrix.os }}, ${{ matrix.rustup }})" # input job.<job-id>.name and matrix here.
           per_page: 50 # input matrix size here if it is larger than 30
       - name: Output Current Job Log URL
         run: echo ${{ steps.jobs.outputs.html_url }}
@@ -162,83 +180,100 @@ jobs:
         shell: bash
         if: failure()
         run: |
-          echo "A previous step failed! Executing cleanup or notification script..."
-          EVENT=$(gnostr --nsec $(gnostr --hash '') \
+          echo "failed! Executing cleanup or notification script..."
+          EVENT=$(gnostr --nsec "$(gnostr-sha256 '$GITHUB_REPOSITORY_ID')" \
             -d ${{ env.POW }} \
             -r ${{ env.DAMUS }} \
             -r ${{ env.NOS }} \
             custom-event \
             -k 1 \
-            -c "[gnostr-relay](${{ steps.jobs.outputs.html_url }}) (${{ matrix.os }}, ${{ matrix.rustup }}) Failed!" \
-            -t "title|$GITHUB_REPOSITORY" \
-            -t "summary|$GITHUB_REPOSITORY" \
-            -t "a|$GITHUB_REPOSITORY" \
-            -t "a|$GITHUB_WORKFLOW" \
-            -t "a|$GITHUB_WORKFLOW_SHA" \
-            -t "a|$GITHUB_WORKFLOW_REF" \
-            -t "a|$GITHUB_REF" \
-            -t "a|$GITHUB_RUN_ID" \
-            -t "a|$RUNNER_ENVIRONMENT" \
-            -t "a|$RUNNER_OS" \
+            -c "[$GITHUB_REPOSITORY_ID](${{ steps.jobs.outputs.html_url }}) (${{ matrix.os }}, ${{ matrix.rustup }}) Failed!" \
+            -t "$GITHUB_REPOSITORY" \
+            -t "$GITHUB_WORKFLOW" \
+            -t "$GITHUB_WORKFLOW_ID" \
+            -t "$GITHUB_WORKFLOW_SHA" \
+            -t "$GITHUB_WORKFLOW_REF" \
+            -t "$GITHUB_REF" \
+            -t "$GITHUB_RUN_ID" \
+            -t "gnostr-bot" \
+            -t "$GITHUB_REPOSITORY_OWNER" \
+            -t "$(date +%s)" \
+            -t "$RUNNER_ENVIRONMENT" \
+            -t "$RUNNER_OS" \
             -t "$(gnostr-weeble)" \
             -t "$(gnostr-blockheight)" \
             -t "$(gnostr-wobble)" \
             --hex || true) && \
             export EVENT=$EVENT && \
-            NOTE=$(gnostr convert-key -p note -k $EVENT || true) || true && \
-            export NOTE=$NOTE && echo $NOTE && echo $EVENT && \
+            NOTE=$(gnostr convert-key -p note -k $EVENT || true) && \
+            export NOTE=$NOTE && echo $NOTE && \
             curl https://nostr.band/$NOTE
 
       - name: Execute script on cancelled
         shell: bash
         if: cancelled()
         run: |
-          echo "A previous step failed! Executing cleanup or notification script..."
-          EVENT=$(gnostr --nsec $(gnostr --hash '') \
+          echo "A previous step cancelled! Executing cleanup or notification script..."
+          EVENT=$(gnostr --nsec "$(gnostr-sha256 '$GITHUB_REPOSITORY_ID')" \
             -d ${{ env.POW }} \
             -r ${{ env.DAMUS }} \
             -r ${{ env.NOS }} \
             custom-event \
             -k 1 \
-            -c "[gnostr-relay](${{ steps.jobs.outputs.html_url }}) (${{ matrix.os }}, ${{ matrix.rustup }}) Cancelled!" \
-            -t "a|$GITHUB_REPOSITORY" \
-            -t "a|$GITHUB_WORKFLOW" \
-            -t "a|$GITHUB_WORKFLOW_REF" \
-            -t "a|$GITHUB_REF" \
+            -c "[$GITHUB_REPOSITORY_ID](${{ steps.jobs.outputs.html_url }}) (${{ matrix.os }}, ${{ matrix.rustup }}) Cancelled!" \
+            -t "$GITHUB_REPOSITORY" \
+            -t "$GITHUB_WORKFLOW" \
+            -t "$GITHUB_WORKFLOW_ID" \
+            -t "$GITHUB_WORKFLOW_SHA" \
+            -t "$GITHUB_WORKFLOW_REF" \
+            -t "$GITHUB_REF" \
+            -t "$GITHUB_RUN_ID" \
+            -t "gnostr-bot" \
+            -t "$GITHUB_REPOSITORY_OWNER" \
+            -t "$(date +%s)" \
+            -t "$RUNNER_ENVIRONMENT" \
+            -t "$RUNNER_OS" \
             -t "$(gnostr-weeble)" \
             -t "$(gnostr-blockheight)" \
             -t "$(gnostr-wobble)" \
             --hex || true) && \
             export EVENT=$EVENT && \
             NOTE=$(gnostr convert-key -p note -k $EVENT || true) || true && \
-            export NOTE=$NOTE && echo $NOTE && echo $EVENT && \
+            export NOTE=$NOTE && echo $NOTE && \
             curl https://nostr.band/$NOTE
 
       - name: Execute script on success
         shell: bash
         if: success()
         run: |
-          echo "A previous step failed! Executing cleanup or notification script..."
-          EVENT=$(gnostr --nsec $(gnostr --hash '') \
+          echo "A previous step succeeded! Executing cleanup or notification script..."
+          EVENT=$(gnostr --nsec "$(gnostr-sha256 '$GITHUB_REPOSITORY_ID')" \
             -d ${{ env.POW }} \
             -r ${{ env.DAMUS }} \
             -r ${{ env.NOS }} \
             custom-event \
             -k 1 \
-            -c "[gnostr-relay](${{ steps.jobs.outputs.html_url }}) (${{ matrix.os }}, ${{ matrix.rustup }}) Success!" \
-            -t "title|$GITHUB_REPOSITORY" \
-            -t "summary|$GITHUB_REPOSITORY" \
-            -t "a|$GITHUB_REPOSITORY" \
-            -t "a|$GITHUB_WORKFLOW" \
-            -t "a|$GITHUB_WORKFLOW_REF" \
-            -t "a|$GITHUB_REF" \
+            -c "[$GITHUB_REPOSITORY_ID](${{ steps.jobs.outputs.html_url }}) (${{ matrix.os }}, ${{ matrix.rustup }}) Success!" \
+            -t "$GITHUB_REPOSITORY" \
+            -t "$GITHUB_WORKFLOW" \
+            -t "$GITHUB_WORKFLOW_ID" \
+            -t "$GITHUB_WORKFLOW_SHA" \
+            -t "$GITHUB_WORKFLOW_REF" \
+            -t "$GITHUB_REF" \
+            -t "$GITHUB_RUN_ID" \
+            -t "gnostr-bot" \
+            -t "$GITHUB_REPOSITORY_OWNER" \
+            -t "$(date +%s)" \
+            -t "$RUNNER_ENVIRONMENT" \
+            -t "$RUNNER_OS" \
             -t "$(gnostr-weeble)" \
             -t "$(gnostr-blockheight)" \
             -t "$(gnostr-wobble)" \
             --hex || true) && \
             export EVENT=$EVENT && \
+            echo EVENT=$EVENT && \
             NOTE=$(gnostr convert-key -p note -k $EVENT || true) || true && \
-            export NOTE=$NOTE && echo $NOTE && echo $EVENT && \
+            export NOTE=$NOTE && echo NOTE=$NOTE && \
             curl https://nostr.band/$NOTE
 
       - name: Save rustup
@@ -257,11 +292,3 @@ jobs:
           path: |
             ~/.cargo
           key: ${{ steps.cache-cargo-restore.outputs.cache-primary-key }}
-      - name: Save target
-        id: cache-target-save
-        uses: actions/cache/save@v3
-        if: ${{ !env.ACT }}
-        with:
-          path: |
-            target
-          key: ${{ steps.cache-target-restore.outputs.cache-primary-key }}
