ci: add debug steps for gnostr installation in gnostr-chat.yml
00-00000ceb

diff --git a/.github/workflows/gnostr-chat.yml b/.github/workflows/gnostr-chat.yml
--- a/.github/workflows/gnostr-chat.yml
+++ b/.github/workflows/gnostr-chat.yml
@@ -96,6 +96,14 @@ jobs:
       - run: cargo search gnostr --limit 100
       - run: cargo install cargo-binstall || true
       - run: cargo-binstall --no-confirm gnostr
+      - name: Debug gnostr installation
+        run: |
+          echo "Verifying cargo-binstall:"
+          which cargo-binstall || echo "cargo-binstall not found or not in PATH."
+          echo "Current PATH: $PATH"
+          echo "Verifying gnostr:"
+          which gnostr || echo "gnostr not found or not in PATH."
+          gnostr --version || true # Run if found, otherwise continue
       - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
         if: matrix.os == 'macos-latest'
       - run: brew tap gnostr-org/homebrew-gnostr-org || true
